# Generated by Django 6.0.6 on 2026-06-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_linkedin_sync_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
