# Generated by Django 6.0.6 on 2026-06-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_lead_ai_reason_lead_ai_score'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deal',
            name='unique_deal_per_campaign',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
