# Generated by Django 6.0.6 on 2026-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0029_actionlog_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='send_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
