# Generated by Django 6.0.6 on 2026-06-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0030_message_send_attempts_message_send_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='billing_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='billing_status',
            field=models.CharField(blank=True, default='active', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='plan',
            field=models.CharField(blank=True, default='self-hosted', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stripe_portal_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='workspace_name',
            field=models.CharField(blank=True, default='Grantgunner', max_length=120),
        ),
    ]
