# Generated by Django 6.0.6 on 2026-06-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0031_siteconfig_billing_email_siteconfig_billing_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='searchkeyword',
            name='campaign',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='linkedin_ta_status_d04eec_idx',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='action_fraction',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='booking_link',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_objective',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='model_blob',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='product_docs',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='seed_public_ids',
        ),
        migrations.DeleteModel(
            name='SearchKeyword',
        ),
    ]
