# Generated by Django 6.0.6 on 2026-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0032_alter_searchkeyword_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
