# Generated by Django 6.0.6 on 2026-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0033_messagethread_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='include_current_network',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadcampaignstate',
            name='connected_via_tool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leadcampaignstate',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped_reply', 'Stopped — replied'), ('stopped_error', 'Stopped — error'), ('paused_manual', 'Paused (manual)'), ('skipped_existing', 'Skipped — existing connection'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
