# Generated by Django 6.0.6 on 2026-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0034_campaign_include_current_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlist',
            name='search_network',
            field=models.CharField(default='S', max_length=20),
        ),
    ]
