# Generated by Django 6.0.6 on 2026-06-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0035_leadlist_search_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sending_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_campaigns', to='linkedin.linkedinprofile'),
        ),
    ]
