# Generated by Django 6.0.6 on 2026-06-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0036_campaign_sending_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='sending_account',
        ),
        migrations.AddField(
            model_name='campaign',
            name='sending_accounts',
            field=models.ManyToManyField(blank=True, related_name='sending_campaigns', to='linkedin.linkedinprofile'),
        ),
        migrations.AddField(
            model_name='leadcampaignstate',
            name='sending_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_states', to='linkedin.linkedinprofile'),
        ),
    ]
