# Generated by Django 6.0.6 on 2026-06-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0037_remove_campaign_sending_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='last_verify_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='last_verify_ok',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='verify_requested',
            field=models.BooleanField(default=False),
        ),
    ]
