# Generated by Django 6.0.6 on 2026-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0038_linkedinprofile_last_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='auto_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
