# Generated by Django 6.0.6 on 2026-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0039_linkedinprofile_auto_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='connect_weekly_limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
