# Generated by Django 6.0.6 on 2026-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0040_linkedinprofile_connect_weekly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcampaignstate',
            name='error_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadcampaignstate',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leadcampaignstate',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
