# Generated by Django 6.0.6 on 2026-06-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0041_leadcampaignstate_error_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='signoff_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
