# Generated by Django 6.0.6 on 2026-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0042_linkedinprofile_signoff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='password_login_ok',
            field=models.BooleanField(default=False),
        ),
    ]
